### ISSUE TITLE
move mocha into devDependencies

### ISSUE THREAD

**Issue by cosmn** [IonicaBizau/remove-blank-lines#11]
its definitely a minor overlooked typing error from the last PR
...or better said command line typo ( --save / --save-dev )
Point is that no one would like having mocha installed on a production build.

`"dependencies": {
    "mocha": "^5.0.4"
}`
to
`"devDependencies": {
    "mocha": "^5.0.4"
}`

Dont forget to publish on npm

**Comment by ainthek** [comment]
Please why is this closed ? mocha is still in dependencies not devDependencies, looking at the package.json. Thanx
